language: php

#cache:
#  directories:
#    - $HOME/.composer/cache/files
#    - $HOME/symfony-bridge/.phpunit

php:
  - 7.2

matrix:
  fast_finish: true
env:
  - SYMFONY_VERSION="4.0.*"

before_install:
  - cp .env.test .env
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction
  - ./vendor/bin/simple-phpunit install

script: ./vendor/bin/simple-phpunit



