language: php

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

php:
  - 7.2

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction
  - ./vendor/bin/simple-phpunit install

script: ./vendor/bin/simple-phpunit



