language: php

services:
  - memcached

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: hhvm

env:
  - SYMFONY_VERSION="4.0.*"

before-install:
  - composer self-update

install:
  - composer install


script:
  - phpunit



