
version: "3.1"
services:
    redis:
      image: redis:latest
      container_name: wonderkind-cache
    symfony:
      build: docker/symfony
      container_name: wonderkind
      working_dir: /app
      volumes:
        - .:/app
      restart: on-failure
      tty: true
      stdin_open: true
      ports:
        - '8000:8000'
      depends_on:
        - redis


